name: Chainlink Price Feed External Adapter
description: Get Price Reference Data from Chainlink Feeds
node_identifier: pricefeed-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Chainlink Price Feeds
    url: https://feeds.chain.link/
parameters:
  - pricePair
  - network
  - priceFeed
