name: Chainlink Price Feed Adapter
description: Get Price Reference Data from Chainlink Feeds
node_identifier: pricefeed-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
parameters:
  - pricePair
  - network
  - priceFeed
