name: Chainlink Price Feed Adapter
description: Price Feeds from Chainlink
node_identifier: pricefeed
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Chainlink Feeds
    url: https://feeds.chain.link/
parameters:
  - pricePair
  - network
  - priceFeed
